### ISSUE TITLE
Will it work with latest changes enacted by twitter? (blocked search for non auth users thus rendering lots of scrapers dead)

### ISSUE THREAD

**Issue by ArtemBernatskyy** [yamin8000/TwitterScrapper#13]
Will it work with latest changes enacted by twitter? (blocked search for non auth users thus rendering lots of scrapers dead)

**Comment by yamin8000** [comment]
> Will it work with latest changes enacted by twitter? (blocked search for non auth users thus rendering lots of scrapers dead)

This tool scraps from Nitter so yeah it works, just test it.
